version: "3.9"

services:
  db:
    image: postgres:15
    container_name: locaza_postgres
    restart: always
    environment:
      POSTGRES_USER: locaza
      POSTGRES_PASSWORD: locaza123
      POSTGRES_DB: locazadb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U locaza -d locazadb"]
      interval: 5s
      timeout: 3s
      retries: 15

  backend:
    build: .
    container_name: locaza_backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: locaza_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@locaza.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: locaza_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
